version: '2'
services:
  transport-postgresql:
    image: postgres:12.1
    # volumes:
    #     - ~/volumes/jhipster/transport/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=transport
      - POSTGRES_PASSWORD=
    ports:
      - 5432:5432
